export type AgentProfile = {
  slug:string; name:string; role:string; phone:string; photo:string; bio:string; specialties:string[]; market:string; snapshot:string; review:string;
};
const legacy='https://s3.amazonaws.com/eap03.easyagentpro.com/wp-content/uploads/sites/1258/2022/06/';
export const agents:AgentProfile[]=[
{slug:'joseph-kirby',name:'Joseph Kirby',role:'Broker',phone:'(785) 559-0551',photo:'https://imagescdn.homes.com/i2/VlE8nl9NFS2ayOgjf-9QtyIDkMrSpXVQnvTPGBqAhNk/117/joseph-kirby.jpg?p=1',bio:'Joseph is the broker behind St. Mary’s Real Estate and works with a wide mix of properties across Northeast Kansas. He helps buyers, sellers, investors and landowners work through the details of a deal, from the first conversation through closing. His experience includes homes, acreage, commercial property, new construction and investment property.',specialties:['Residential','Land & acreage','Investments','Commercial','New construction','Property management'],market:'St. Marys · Wamego · Rossville · Topeka · Manhattan · Northeast Kansas',snapshot:'Public transaction data shows 67 closed sales and about $14.5 million in transaction value over the prior five years.',review:'Clients have described Joseph as patient, communicative and easy to work with, including first-time buyers and people managing a sale and purchase at the same time.'},
{slug:'thomas-kirby',name:'Thomas Kirby',role:'Agent',phone:'(785) 338-3597',photo:'https://imagescdn.homes.com/i2/QhGSzGRJ8kH-kdLwGNn_jTq5oF2twBazWYJPXOfQ3t0/117/thomas-kirby.jpg?p=1',bio:'Thomas works primarily with residential and land clients around St. Marys, Wamego, Topeka and Manhattan. He has a particular interest in homes, architecture and the practical details that can make a property a good fit or a poor one. Clients can expect straightforward communication, local context and a hands-on approach throughout the process.',specialties:['Residential','Land & acreage','First-time buyers','Investments','Rural property'],market:'St. Marys · Wamego · Topeka · Manhattan · Emmett · surrounding rural communities',snapshot:'Public transaction data shows 64 closed sales and about $15.5 million in transaction value over the prior five years.',review:'A published SMRE review from an out-of-state buyer specifically praised Thomas and the team for careful remote walkthroughs and for helping the buyers understand the condition of a home before they arrived.'},
{slug:'james-frazier',name:'James Frazier',role:'Associate Broker',phone:'(936) 661-3227',photo:`${legacy}06132539/IMG_9091_Edited-1-150x150.jpg`,bio:'James is an associate broker who works with residential buyers and sellers in the Topeka, Wamego and Manhattan areas. His transaction history includes homes in town as well as properties with more room and acreage, so his work often crosses between traditional residential neighborhoods and rural communities.',specialties:['Residential','Rural homes','Topeka area','Wamego','Manhattan area'],market:'Topeka · Wamego · Manhattan · Paxico · surrounding communities',snapshot:'Public transaction data shows 7 closed sales and about $1.1 million in transaction value over the prior five years.',review:'The public review material available for SMRE is largely company-wide, so this profile only summarizes themes that can be tied to the brokerage rather than assigning an unverified testimonial to James.'},
{slug:'michael-kirby',name:'Michael Kirby',role:'Agent',phone:'(785) 491-0576',photo:`${legacy}01135934/IMG-0256-1.jpg`,bio:'Michael works with buyers and sellers around St. Marys and the surrounding communities. His public transaction history includes residential property in St. Marys and Emmett, and his client feedback highlights the kind of hands-on help that matters when someone is new to the area and needs a local point of contact.',specialties:['Residential','Buyer representation','Relocation','St. Marys area','Emmett area'],market:'St. Marys · Emmett · surrounding Northeast Kansas communities',snapshot:'Public transaction data currently shows 8 sales in the available Homes.com transaction history.',review:'One published client review describes Michael as making an out-of-state buyer’s purchase easy to navigate, answering questions promptly and helping connect the buyer with dependable local professionals.'}
];
export function getAgent(slug:string){return agents.find(a=>a.slug===slug);}
