export type AgentProfile = {
  slug:string; name:string; role:string; phone:string; photo:string; bio:string; specialties:string[]; market:string; snapshot:string; review:string;
};
const s3='https://s3.amazonaws.com/eap03.easyagentpro.com/wp-content/uploads/sites/1258/2022/06/';
export const agents:AgentProfile[]=[
{slug:'joseph-kirby',name:'Joseph Kirby',role:'Broker',phone:'(785) 559-0551',photo:`${s3}05113808/Joseph-Profile-picture-03-crop-google-profile.jpg`,bio:'Joseph is the principal broker of St. Mary’s Real Estate and works across residential, land, commercial, investment, new-construction and property-management transactions. His recent transaction history spans St. Marys, Wamego, Rossville, Delia and other communities across northeast Kansas.',specialties:['Residential','Land & acreage','Investments','Commercial','New construction','Property management'],market:'St. Marys · Wamego · Rossville · Topeka · Manhattan · Northeast Kansas',snapshot:'Public transaction data currently shows 67 closed sales and about $14.5 million in transaction value over the prior five years.',review:'Client feedback on the brokerage site repeatedly points to Joseph’s communication, patience and hands-on guidance, including with first-time buyers and clients managing a purchase and sale at the same time.'},
{slug:'thomas-kirby',name:'Thomas Kirby',role:'Agent',phone:'(785) 338-3597',photo:`${s3}01140013/IMG_0254-1.jpg`,bio:'Thomas is a residential and land agent serving the St. Marys, Wamego, Manhattan and Topeka areas. His public profile emphasizes local market knowledge, architecture and practical guidance for buyers, sellers, first-time homeowners and investors. His recent transactions include homes, acreage and rural properties throughout the region.',specialties:['Residential','Land & acreage','First-time buyers','Investments','Rural property'],market:'St. Marys · Wamego · Emmett · Topeka · Manhattan · surrounding rural communities',snapshot:'A current public agent profile shows 64 closed sales and about $18.2 million in total value.',review:'A published client review describing an out-of-state purchase specifically praised Thomas and the team for careful remote walkthroughs, pointing out property condition details and helping the buyers understand the home before they arrived.'},
{slug:'james-frazier',name:'James Frazier',role:'Associate Broker',phone:'(936) 661-3227',photo:`${s3}22103828/James-profile-photo-2.jpg`,bio:'James is an associate broker working primarily across the Topeka, Wamego and Manhattan markets. Public transaction records show experience with residential property in communities including Wamego, Southwest Topeka, South Manhattan, Monroe and Paxico, giving him exposure to both town and rural-area transactions.',specialties:['Residential','Rural homes','Topeka area','Wamego','Manhattan area'],market:'Topeka · Wamego · Manhattan · Paxico · surrounding communities',snapshot:'Public transaction data shows 7 closed sales and about $1.1 million in total value over the prior five years.',review:'The available public review material for SMRE is largely company-wide rather than agent-specific, so this profile does not attribute a testimonial to James that cannot be verified.'},
{slug:'michael-kirby',name:'Michael Kirby',role:'Agent',phone:'(785) 491-0576',photo:`${s3}01135934/IMG-0256-1.jpg`,bio:'Michael works with buyers and sellers in St. Marys and the surrounding northeast Kansas communities. Public transaction records include residential work in St. Marys and Emmett, and client feedback specifically describes his work with a buyer who had recently moved to the area from another state.',specialties:['Residential','Buyer representation','Relocation','St. Marys area','Emmett area'],market:'St. Marys · Emmett · surrounding northeast Kansas communities',snapshot:'Public transaction data currently shows 8 sales in the available Homes.com transaction history.',review:'A published client review describes Michael as making an out-of-state buyer’s purchase easy to navigate, with responsive answers and useful recommendations for local professionals.'}
];
export function getAgent(slug:string){return agents.find(a=>a.slug===slug);}
