export type AgentProfile = {
  slug:string; name:string; role:string; phone:string; photo:string; bio:string; specialties:string[]; market:string; snapshot:string; review:string;
};
const legacy='https://s3.amazonaws.com/eap03.easyagentpro.com/wp-content/uploads/sites/1258/2022/06/';
export const agents:AgentProfile[]=[
{slug:'joseph-kirby',name:'Joseph Kirby',role:'Broker',phone:'(785) 559-0551',photo:'https://imagescdn.homes.com/i2/VlE8nl9NFS2ayOgjf-9QtyIDkMrSpXVQnvTPGBqAhNk/117/joseph-kirby.jpg?p=1',bio:'Joseph Kirby is a full-time real estate professional and the principal broker of St. Mary’s Real Estate. His public Realtor.com profile describes his work with residential, land and commercial buyers and sellers throughout Northeast Kansas, along with investments, first-time buyers, new construction, resale and property management. He also serves on the Sunflower MLS Board of Directors.',specialties:['Residential','Land & acreage','Investments','Commercial','New construction','Property management'],market:'St. Marys · Wamego · Rossville · Topeka · Manhattan · Northeast Kansas',snapshot:'Public profiles describe Joseph as a full-time real estate professional and principal broker serving Northeast Kansas.',review:'Published SMRE reviews describe Joseph helping clients through both sales and purchases, including first-time buyers, with communication throughout the process.'},
{slug:'thomas-kirby',name:'Thomas Kirby',role:'Agent',phone:'(785) 338-3597',photo:'https://imagescdn.homes.com/i2/QhGSzGRJ8kH-kdLwGNn_jTq5oF2twBazWYJPXOfQ3t0/117/thomas-kirby.jpg?p=1',bio:'Thomas Kirby is a residential and land agent serving the Manhattan-to-Topeka communities. His public profile says he has a strong appreciation for architecture and takes pride in staying up to date on market trends and real estate technology. Outside of real estate, he enjoys hiking and biking and often incorporates his love of the outdoors into his work. He focuses on making the buying or selling process smooth and less stressful while helping clients understand the local market.',specialties:['Residential','Land & acreage','First-time buyers','Investments','Rural property'],market:'St. Marys · Wamego · Topeka · Manhattan · Emmett · surrounding rural communities',snapshot:'Public profiles describe Thomas as a residential and land agent serving the Manhattan-to-Topeka area.',review:'A published SMRE review from an out-of-state buyer specifically mentions Thomas and the team providing careful remote walkthroughs and helping the buyers understand the condition of a home before arriving.'},
{slug:'james-frazier',name:'James Frazier',role:'Associate Broker',phone:'(936) 661-3227',photo:`${legacy}22103828/James-profile-photo-2.jpg`,bio:'James Frazier is an associate broker with St. Mary’s Real Estate. His public professional profile describes his work as real estate sales and marketing in Kansas, following previous work in Texas. He is based in St. Marys and works with the brokerage’s buyers and sellers throughout the area.',specialties:['Residential','Rural homes','Topeka area','Wamego','Manhattan area'],market:'Topeka · Wamego · Manhattan · St. Marys · surrounding communities',snapshot:'James is publicly listed as an Associate Broker with St. Mary’s Real Estate.',review:'The public review material available for SMRE is largely company-wide, so this profile does not assign an individual testimonial to James without a source.'},
{slug:'michael-kirby',name:'Michael Kirby',role:'Agent',phone:'(785) 491-0576',photo:`${legacy}01135934/IMG-0256-1.jpg`,bio:'Michael Kirby is an agent with St. Mary’s Real Estate serving buyers and sellers in St. Marys and the surrounding area. Public brokerage material shows him working with clients who are new to the area and helping them find a home, work through the purchase process, answer questions and connect with local service providers.',specialties:['Residential','Buyer representation','Relocation','St. Marys area','Emmett area'],market:'St. Marys · Emmett · surrounding Northeast Kansas communities',snapshot:'Michael is publicly listed as an Agent with St. Mary’s Real Estate.',review:'One published client review describes Michael as making an out-of-state buyer’s purchase easy to navigate, answering questions and helping connect the buyer with local professionals.'}
];
export function getAgent(slug:string){return agents.find(a=>a.slug===slug);}
