export type Guide={slug:string;title:string;category:string;description:string;intro:string;sections:{heading:string;body:string}[]};

export const guides:Guide[]=[
{slug:'buying-land-pottawatomie-county',title:'Buying Land in Pottawatomie County',category:'LAND & ACREAGE',description:'A practical overview of what to check before buying land in Pottawatomie County, Kansas.',intro:'Buying land is different from buying a finished home. In Pottawatomie County, zoning, water, sanitation, road access, floodplain status and subdivision rules can all affect whether a parcel is usable for your plans. Before making an offer, verify the specific tract with Planning and Zoning rather than relying only on acreage or an old listing.',sections:[
{heading:'Start with the property’s intended use',body:'Think through the end use first. Building a home, adding a shop, keeping livestock, splitting the property or simply holding acreage can lead to different questions about zoning, access, utilities and subdivision requirements. Pottawatomie County's A1 agricultural district treats agricultural uses differently from non-farm residential development, so the zoning designation and proposed use matter.'},
{heading:'Check water and septic options',body:'For A1 agricultural tracts, the County generally states a minimum of 3 acres when rural water is available and 5 acres when the tract will use an individual well, but the final tract size is based on water availability and sanitary disposal needs. The County also requires verification of public water availability for certain building permits on lots under 5 acres. Do not treat 3 or 5 acres as a blanket guarantee that a house can be built.'},
{heading:'Verify access and roads',body:'Legal access is not always the same thing as a road that is ready for construction. County subdivision standards address public-road access, road construction and emergency access, and flag lots are generally not permitted unless waived by the County Planner. Check frontage, easements, road classification and access requirements for the specific tract.'},
{heading:'Look beyond the price per acre',body:'Two parcels with the same price per acre can have very different values once you account for utilities, driveway work, fencing, topography, drainage, timber, building sites and development restrictions. Floodplain status can also materially affect a building site and should be checked before assuming all of the acreage is equally usable.'}
]},
{slug:'rural-water-vs-private-well',title:'Rural Water vs. Private Well in Pottawatomie County',category:'LAND & ACREAGE',description:'What buyers should consider when a rural Kansas property has rural water or a private well.',intro:'Water is one of the first things to investigate when buying rural property. The right choice depends on the property, available infrastructure, ongoing costs and what you plan to do with the land.',sections:[
{heading:'Rural water',body:'A rural water connection can provide a centralized water source without maintaining a private well. For proposed subdivisions, Pottawatomie County states that if a rural water district is within one-half mile, connection is required unless the district determines service is not feasible. For an individual tract, verify actual service availability and connection requirements with the water district.'},
{heading:'Private wells',body:'A private well can make sense where rural water is unavailable, but the buyer should understand the well’s age, depth, production, water quality and equipment. In the County's A1 district, individual-well residential tracts generally require at least 5 acres, subject to the County's sanitary and water-availability determinations.'},
{heading:'Ask before you buy',body:'Do not assume a water line is available simply because one is nearby. Confirm service availability directly with the applicable water district and understand what the buyer will be responsible for paying to connect. Water availability can also affect the minimum tract size and whether a proposed homesite is practical.'}
]},
{slug:'septic-systems-rural-kansas',title:'What to Know About Septic Systems in Rural Kansas',category:'LAND & ACREAGE',description:'The basic septic and soil questions to ask before buying rural property in Northeast Kansas.',intro:'A rural property without public sewer needs an approved wastewater solution. The most important question is not simply whether the property has a septic system, but whether the site can support the intended use.',sections:[
{heading:'Existing systems',body:'For an existing home, find out where the tank and lateral field are located and ask about installation, maintenance and pumping history. A septic inspection can identify conditions that are not obvious during a normal home inspection.'},
{heading:'Vacant land',body:'For vacant land, confirm that the site can support an approved wastewater system before treating it as a buildable homesite. County subdivision review may require soils or profile analysis, percolation information and drainage information for sanitary review. The County's sanitation code also requires an approved plan and inspection before a new or modified septic system is covered.'},
{heading:'County requirements',body:'Requirements can change by property and can depend on the water source and proposed use. Pottawatomie County Planning and Zoning administers the County's zoning and subdivision regulations, while sanitary requirements are reviewed through the County's environmental health process. Verify the current requirements before closing on land based on an assumption about septic feasibility.'}
]},
{slug:'buying-acreage-near-st-marys',title:'Buying Acreage Near St. Marys, Kansas',category:'LOCAL BUYING',description:'A practical checklist for buyers looking at homes, farms and acreage around St. Marys.',intro:'Acreage around St. Marys can offer more space, outbuildings and privacy, but rural property comes with a different set of questions than an in-town home. In unincorporated Pottawatomie County, the applicable zoning district and the property's water and sanitation situation can affect whether a parcel is suitable for a home.',sections:[
{heading:'Decide what you actually need',body:'Start with the reason you want acreage. A buyer looking for room for a shop has different priorities than someone looking for pasture, hunting ground or a future homesite.'},
{heading:'Evaluate the homesite',body:'Look at driveway access, drainage, topography, utility locations, trees, outbuildings and the practical location of a future or existing home. A large parcel does not automatically mean it has a good building site. Check floodplain maps and whether the proposed building location meets required setbacks and sanitary separation requirements.'},
{heading:'Understand ongoing costs',body:'Acreage can mean additional mowing, fencing, driveway maintenance, equipment and outbuilding upkeep. Include those costs when comparing rural property with homes on smaller lots.'}
]},
{slug:'st-marys-housing-market',title:'St. Marys, KS Housing Market',category:'LOCAL MARKET',description:'A local overview of the St. Marys residential market and the factors that affect pricing.',intro:'Real estate in St. Marys is influenced by a relatively small inventory of homes, local demand and the condition and characteristics of each property. Broad national trends do not always describe what is happening here.',sections:[
{heading:'Inventory matters',body:'In a smaller market, a few active listings can materially change the choices available to buyers. Limited inventory can support prices for well-positioned homes, while properties with condition or location issues may behave differently.'},
{heading:'Condition matters more than averages',body:'Two homes with similar square footage can have very different values because of updates, layout, lot, basement, garage, outbuildings and overall condition. Local comparable sales are more useful than applying a broad price-per-square-foot number.'},
{heading:'For sellers',body:'Pricing should account for the current competition as well as recent sales. Presentation, condition and the property’s specific buyer pool can affect how quickly a home attracts serious interest.'}
]},
{slug:'wamego-housing-market',title:'Wamego, KS Housing Market',category:'LOCAL MARKET',description:'What buyers and sellers should consider when looking at the Wamego housing market.',intro:'Wamego has its own market dynamics, even though it is part of the broader Topeka-Manhattan area. Location, school considerations, new construction and limited inventory can all influence pricing.',sections:[
{heading:'Compare the right properties',body:'A useful comparable sale should be similar in location, size, age, condition and features. A sale several miles away or in a very different neighborhood may not tell you much about a specific Wamego property.'},
{heading:'New construction and existing homes',body:'New construction can affect buyer expectations for existing homes. When comparing properties, consider what a buyer receives in terms of finishes, energy efficiency, warranty and maintenance.'},
{heading:'Local advice matters',body:'Market conditions can change quickly in a smaller community. A current review of active competition and recent closed sales is more useful than relying on a national market headline.'}
]},
{slug:'buying-home-between-topeka-and-manhattan',title:'Buying a Home Between Topeka and Manhattan',category:'LOCAL BUYING',description:'How to approach a home search across the communities between Topeka and Manhattan.',intro:'The Topeka-Manhattan corridor gives buyers more options than a single-city search, but commuting distance, services and community differences can quickly change what makes a property a good fit. If you are considering acreage outside city limits, add zoning, water, septic, road access and floodplain questions to the normal home-buying checklist.',sections:[
{heading:'Think in terms of your actual commute',body:'Map the places you regularly need to reach rather than choosing a town based only on its distance from Topeka or Manhattan. Work schedules and road access can make a meaningful difference.'},
{heading:'Compare communities, not just houses',body:'Consider schools, shopping, healthcare, recreation, internet availability and the type of property available in each community. A slightly different location may offer a much better fit.'},
{heading:'Use a focused search',body:'Start with the areas that work for your daily life, then compare homes within those areas. This keeps a regional search from becoming a long list of properties that look good on paper but do not work in practice.'}
]},
{slug:'selling-home-st-marys',title:'Selling a Home in St. Marys',category:'LOCAL SELLING',description:'A straightforward guide to preparing and pricing a home for sale in St. Marys.',intro:'Selling a home in a smaller local market is not about copying a national checklist. The goal is to understand the current competition, price the property appropriately and make it easy for the right buyers to see its value.',sections:[
{heading:'Start with the market',body:'Look at recent comparable sales, current competing listings and properties that recently went under contract. The combination gives you a better picture than any single sale.'},
{heading:'Fix the right things',body:'Not every repair is worth making before a sale. Focus first on items that affect safety, financing, obvious condition concerns and the buyer’s first impression.'},
{heading:'Present the property clearly',body:'Good photography, accurate information and a clear description help buyers understand the property before they schedule a showing. For unique homes or acreage, showing the features that actually differentiate the property is especially important.'}
]},
{slug:'first-time-home-buyer-northeast-kansas',title:'Buying Your First Home in Northeast Kansas',category:'LOCAL BUYING',description:'A practical starting point for first-time buyers shopping in the Topeka-Manhattan area.',intro:'Buying your first home can feel complicated because there are several decisions happening at once. A good process starts with understanding your budget, financing and the type of property that actually fits your life.',sections:[
{heading:'Know your comfortable payment',body:'A lender can tell you what you qualify for, but the maximum approval is not necessarily the right budget. Consider taxes, insurance, utilities, maintenance and other monthly obligations.'},
{heading:'Get financing lined up early',body:'A preapproval gives you a realistic price range and makes it easier to act when the right home appears. Ask your lender about loan programs, down payment requirements and estimated closing costs.'},
{heading:'Look at the whole property',body:'The purchase price is only part of the decision. Consider condition, future maintenance, location, taxes, insurance and the cost of improvements when comparing homes.'}
]},
{slug:'buying-land-northeast-kansas',title:'Buying Land in Northeast Kansas',category:'LAND & ACREAGE',description:'Questions to answer before buying acreage, a homesite or investment land in Northeast Kansas.',intro:'Land can look simple on a listing sheet, but the details that determine its usefulness are often less obvious. In Pottawatomie County, investigate the zoning district, water source, sanitary disposal, road access, floodplain status, setbacks and any recorded restrictions before making an offer.',sections:[
{heading:'Confirm what you can do with it',body:'Check zoning, minimum tract sizes, subdivision rules, building restrictions and any recorded covenants that could affect your plans. In A1 agricultural zoning, the County generally allows two non-farm dwellings per quarter-quarter section. More than two residential dwellings in a quarter-quarter generally triggers the subdivision process, subject to the specific A1 exceptions and current County review.'},
{heading:'Investigate utilities',body:'Determine whether the property has public or rural water, electricity, sewer or septic options. For subdivisions, County rules address rural-water availability, public sewer connections, interior roads and infrastructure assurances. Get actual service information rather than assuming nearby infrastructure can be extended.'},
{heading:'Consider future value carefully',body:'Development potential can add value, but it also comes with costs and approvals. Understand the practical path to development before paying a premium for an assumed future use.'}
]},
{slug:'five-acres-pottawatomie-county',title:'What Does 5 Acres Actually Get You in Pottawatomie County?',category:'LAND & ACREAGE',description:'Five acres can mean very different things depending on zoning, utilities, access and the property itself.',intro:'A five-acre parcel sounds straightforward, but acreage alone does not tell you whether a property is a good homesite, how many structures may be possible or what development work will be required.',sections:[
{heading:'Acreage is only the starting point',body:'The usable portion of a parcel may be reduced by slopes, drainage, easements, setbacks, ponds, roads or required utility areas. The County's subdivision regulations also call for a 100-foot building setback from the thread of a stream, while individual zoning districts can impose additional setbacks.'},
{heading:'Check zoning and development rules',body:'Minimum tract size is only one piece of the puzzle. In A1, two non-farm dwellings are permitted per quarter-quarter section, and residential development of more than two houses in a quarter-quarter generally must be platted and subdivided. Confirm current zoning, dwelling limits, subdivision requirements and road standards for the specific property.'},
{heading:'Plan for the entire site',body:'Before buying, sketch out the likely home, driveway, septic area, outbuildings and other improvements. A parcel that looks large from the road may have fewer practical building options than expected.'}
]}
];

export function getGuide(slug:string){return guides.find(g=>g.slug===slug);}

export const countySources=[{label:'Pottawatomie County Unified Development Regulations',url:'https://www.pottcounty.org/DocumentCenter/View/10064/Updated-Complete-UDR-2023-Digital'},{label:'Pottawatomie County Regulations',url:'https://www.pottcounty.org/537/Regulations'},{label:'Pottawatomie County Planning & Zoning',url:'https://www.pottcounty.org/161/Planning-Zoning-Office'}];
