export type MLSSource = 'Sunflower MLS' | 'FHAR MLS';
export type PropertyType = 'Residential' | 'Farm' | 'Land' | 'Commercial';
export interface RESOMedia { MediaKey:string; MediaURL:string; MediaCategory:'Photo'; ShortDescription?:string; }
export interface RESOProperty {
 ListingId:string; StandardStatus:'Active'|'Pending'|'Closed'; ListPrice:number; BedroomsTotal:number; BathroomsTotalInteger:number; PropertyType:PropertyType; PropertySubType:string; StreetNumber:string; StreetName:string; City:string; StateOrProvince:string; PostalCode:string; LivingArea:number; LotSizeAcres:number; YearBuilt:number; PublicRemarks:string; Media:RESOMedia[]; ListingKey:string; ListAgentFullName:string; ListAgentMlsId:string; ListOfficeName:string; MlsSource:MLSSource; Latitude:number; Longitude:number;
 BathroomsFull?:number; BathroomsHalf?:number; PricePerSqFt?:number; AnnualTaxes?:number; TaxYear?:number; LotSizeSqFt?:number; GarageSpaces?:number; ParkingFeatures?:string; Basement?:string; Foundation?:string; Roof?:string; Exterior?:string; Flooring?:string; Appliances?:string; Heating?:string; Cooling?:string; WaterSource?:string; Sewer?:string; HOA?:string; Schools?:string; Directions?:string; ArchitecturalStyle?:string; ListingDate?:string; MLSNumber?:string; ParcelNumber?:string; OtherStructures?:string; Features?:string[];
}
const photos=['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=88','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=88','https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=88'];
export const mockProperties:RESOProperty[]=[
 {ListingId:'244039',ListingKey:'244039',StandardStatus:'Active',ListPrice:290000,BedroomsTotal:3,BathroomsTotalInteger:2,BathroomsFull:2,BathroomsHalf:1,PropertyType:'Residential',PropertySubType:'Single Family Residence',StreetNumber:'802',StreetName:'W Bertrand Ave',City:'St. Marys',StateOrProvince:'KS',PostalCode:'66536',LivingArea:2382,LotSizeAcres:.30,LotSizeSqFt:13068,YearBuilt:1920,PricePerSqFt:122,AnnualTaxes:2265.68,TaxYear:2025,PublicRemarks:'Welcome to this versatile 3 bedroom, 2.5 bath home with a detached studio ADU, offering flexibility for guests, extended family, a home office or rental income. The main home features hardwood floors, an updated kitchen, a new half bath downstairs and two full baths upstairs. The main-level laundry room includes additional workspace, and the basement includes a storm shelter. Outside, a patio opens to a private backyard.',Media:photos.map((url,j)=>({MediaKey:`244039-${j}`,MediaURL:url,MediaCategory:'Photo'})),ListAgentFullName:'Thomas Kirby',ListAgentMlsId:'T-1002',ListOfficeName:'St. Mary’s Real Estate',MlsSource:'Sunflower MLS',Latitude:39.1917,Longitude:-96.0660,GarageSpaces:0,ParkingFeatures:'Off-street parking',Basement:'Concrete, full, unfinished, storm shelter',Foundation:'Concrete',Roof:'Composition',Exterior:'Frame, vinyl siding',Flooring:'Hardwood, ceramic tile, carpet',Appliances:'Electric range, dishwasher, refrigerator',Heating:'Forced gas',Cooling:'Central air',WaterSource:'Public',Sewer:'Public sewer',HOA:'No HOA',Schools:'St. Marys Elementary · St. Marys Middle · St. Marys High',Directions:'See MLS directions',ArchitecturalStyle:'Two story',ListingDate:'2026-04-17',MLSNumber:'244039',ParcelNumber:'272-09-0-40-01-003.01-0',OtherStructures:'Detached studio ADU',Features:['No HOA','Fireplace','Patio','Formal dining room','Thermal pane windows','Main-level laundry','Storm shelter','Detached studio ADU']},
 {ListingId:'246333',ListingKey:'246333',StandardStatus:'Active',ListPrice:299000,BedroomsTotal:3,BathroomsTotalInteger:2,BathroomsFull:2,BathroomsHalf:1,PropertyType:'Residential',PropertySubType:'Single Family Residence',StreetNumber:'701',StreetName:'W Durink St',City:'St. Marys',StateOrProvince:'KS',PostalCode:'66536',LivingArea:1456,LotSizeAcres:.16,LotSizeSqFt:6970,YearBuilt:2022,PricePerSqFt:205.36,AnnualTaxes:1696.74,TaxYear:2025,PublicRemarks:'Built in 2022 and move-in ready, this low-maintenance home offers 3 bedrooms, 2.5 bathrooms and a quiet corner-lot setting. The bright, open interior has plenty of natural light and a clean, comfortable layout. Outside, the backyard has room to play, relax or entertain, with a concrete patio just off the back door.',Media:photos.map((url,j)=>({MediaKey:`246333-${j}`,MediaURL:url,MediaCategory:'Photo'})),ListAgentFullName:'Thomas Kirby',ListAgentMlsId:'T-1002',ListOfficeName:'St. Mary’s Real Estate',MlsSource:'FHAR MLS',Latitude:39.194,Longitude:-96.063,GarageSpaces:0,ParkingFeatures:'Driveway',Basement:'Slab; no basement',Foundation:'Slab',Roof:'Architectural shingle',Exterior:'Hardboard siding',Flooring:'See MLS',Appliances:'See MLS',Heating:'Natural gas',Cooling:'Central air',WaterSource:'City water',Sewer:'City sewer',HOA:'No HOA',Schools:'Kaw Valley USD 321',Directions:'Hwy 24 to St Marys, north on Hwy 63, west on Durink Street to 701 Durink. Corner of 7th St and Durink St.',ArchitecturalStyle:'Two story',ListingDate:'2026-08-29',MLSNumber:'FHR20262348',ParcelNumber:'272-10-0-20-25-009.00-0',OtherStructures:'None',Features:['No HOA','2022 construction','Corner lot','Main-level laundry','Dining room','Living room','Central air']},
 {ListingId:'245430',ListingKey:'245430',StandardStatus:'Active',ListPrice:475000,BedroomsTotal:6,BathroomsTotalInteger:3,BathroomsFull:3,BathroomsHalf:1,PropertyType:'Residential',PropertySubType:'Single Family Residence',StreetNumber:'17320',StreetName:'C Rd',City:'Delia',StateOrProvince:'KS',PostalCode:'66418',LivingArea:2372,LotSizeAcres:8.95,YearBuilt:2012,PricePerSqFt:200,PublicRemarks:'Expansive walk-out ranch on approximately 9 scenic acres with 6 bedrooms, 3.5 bathrooms, finished lower-level space, a wrap-around deck and country views. The property offers room for recreation, animals, outbuildings and rural living while remaining within the broader St. Marys–Topeka area.',Media:photos.map((url,j)=>({MediaKey:`245430-${j}`,MediaURL:url,MediaCategory:'Photo'})),ListAgentFullName:'Joseph Kirby',ListAgentMlsId:'J-1001',ListOfficeName:'St. Mary’s Real Estate',MlsSource:'FHAR MLS',Latitude:39.35,Longitude:-95.91,Features:['Walk-out ranch','Approximately 9 acres','Wrap-around deck','Country views','Finished lower-level space'],ListingDate:'2026-04-01',MLSNumber:'FHAR public listing snapshot'}
];
export function getMockProperty(id:string){return mockProperties.find(p=>p.ListingId===id||p.ListingKey===id);}
// LIVE RESO GO-LIVE NOTES:
// These records are current public listing snapshots used until the authorized Sunflower/FHAR RESO feeds are connected.
// 1) Obtain IDX approval + RESO Web API credentials from BOTH Sunflower MLS and FHAR MLS.
// 2) Store credentials only in Vercel server environment variables (never NEXT_PUBLIC_*).
// 3) Implement two server-side RESO clients, normalize both feeds to RESOProperty, and merge/dedupe by ListingKey/ListingId.
// 4) Replace this file's mock data source with the normalized backend response; frontend contracts do not need to change.
