'use client';
import {useEffect,useMemo,useState} from 'react';
import {AdminAnalytics} from './AdminAnalytics';

type Lead={id:string;createdAt:string;type:string;name:string;email?:string;phone?:string;address?:string;listingId?:string;message?:string;status:'new'|'contacted'|'closed';assignedAgent?:string;notes?:string;lastContactedAt?:string;nextFollowUpAt?:string};
type Agent={slug:string;name:string;role:string;phone:string;photo:string;bio:string;specialties:string[];market:string;snapshot:string;review:string;email?:string;hidden?:boolean;sort?:number};
type Guide={slug:string;title:string;category:string;description:string;intro:string;updated:string;sections:{heading:string;body:string}[];sources?:{label:string;url:string}[];draft?:boolean};
type Testimonial={id:string;name:string;quote:string;rating:number;source:string;date?:string;featured:boolean;sort:number};
type Settings={phone:string;address:string;email:string;homepageHeadline:string;officeHours:string;facebook:string;instagram:string;youtube:string;googleBusiness:string;defaultTitle:string;defaultDescription:string;ogImage:string;leadNotificationEmail:string;heroEyebrow:string;heroDescription:string;localHeading:string;localDescription:string;localImage:string;featuredCount:number};
type Data={settings:Settings;agents:Agent[];guides:Guide[];leads:Lead[];testimonials:Testimonial[];updatedAt?:string};
type Media={url:string;pathname:string;size?:number;uploadedAt?:string};

const tabs=[['dashboard','Dashboard'],['analytics','Analytics'],['leads','Leads'],['agents','Agents'],['guides','Guides'],['testimonials','Testimonials'],['homepage','Homepage'],['media','Media'],['settings','Settings']] as const;

export function AdminDashboard(){
 const [data,setData]=useState<Data|null>(null);const [section,setSection]=useState('dashboard');const [message,setMessage]=useState('');const [selectedLead,setSelectedLead]=useState<string|null>(null);
 useEffect(()=>{fetch('/api/admin/data',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(setData).catch(()=>setMessage('Unable to load admin data.'));},[]);
 async function save(next:Data){setMessage('Saving…');const r=await fetch('/api/admin/data',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(next)});if(r.ok){const fresh=await r.json();setData(fresh);setMessage('Saved.')}else setMessage('Save failed.');}
 if(!data)return <main className="admin-shell"><div className="admin-loading">{message||'Loading…'}</div></main>;
 const newLeads=data.leads.filter(l=>l.status==='new').length;
 const showing=data.leads.filter(l=>l.type==='Showing Request').length;
 const followups=data.leads.filter(l=>l.nextFollowUpAt).length;
 return <main className="admin-shell"><div className="admin-layout">
  <aside className="admin-nav"><div><p className="eyebrow">SMRE ADMIN</p><h2>Website</h2></div>{tabs.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}{id==='leads'&&newLeads>0?<b>{newLeads}</b>:null}</button>)}<button onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});location.href='/admin/login'}}>Sign out</button></aside>
  <section className="admin-main"><div className="admin-top"><div><p className="eyebrow">ST. MARY’S REAL ESTATE</p><h1>{tabs.find(x=>x[0]===section)?.[1]}</h1></div><span className="admin-save">{message}</span></div>
   {section==='dashboard'&&<Dashboard data={data} setSection={setSection}/>}
   {section==='analytics'&&<AdminAnalytics/>}
   {section==='leads'&&<Leads data={data} save={save} selectedLead={selectedLead} setSelectedLead={setSelectedLead}/>}
   {section==='agents'&&<Agents data={data} save={save}/>}
   {section==='guides'&&<Guides data={data} save={save}/>}
   {section==='testimonials'&&<Testimonials data={data} save={save}/>}
   {section==='homepage'&&<Homepage data={data} save={save}/>}
   {section==='media'&&<Media/>}
   {section==='settings'&&<Settings data={data} save={save}/>}
  </section>
 </div></main>;
}

function Dashboard({data,setSection}:{data:Data;setSection:(s:string)=>void}){
 const recent=[...data.leads].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,6);
 return <div className="admin-dashboard"><div className="admin-cards"><Stat n={data.leads.filter(l=>l.status==='new').length} label="New leads" onClick={()=>setSection('leads')}/><Stat n={data.leads.filter(l=>l.type==='Showing Request').length} label="Showing requests" onClick={()=>setSection('leads')}/><Stat n={data.agents.filter(a=>!a.hidden).length} label="Active agents" onClick={()=>setSection('agents')}/><Stat n={data.guides.filter(g=>!g.draft).length} label="Published guides" onClick={()=>setSection('guides')}/></div>
 <div className="admin-dashboard-grid"><div className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">RECENT LEADS</p><h2>Latest inquiries</h2></div><button className="admin-link-button" onClick={()=>setSection('leads')}>View all</button></div>{recent.length?<div className="admin-recent-list">{recent.map(l=><button key={l.id} onClick={()=>setSection('leads')}><span><strong>{l.name}</strong><small>{l.type} · {new Date(l.createdAt).toLocaleDateString()}</small></span><em className={'lead-status '+l.status}>{l.status}</em></button>)}</div>:<p className="admin-muted">No leads yet.</p>}</div>
 <div className="admin-panel"><div className="admin-panel-head"><div><p className="eyebrow">QUICK ACTIONS</p><h2>Manage the site</h2></div></div><div className="admin-quick-actions"><button onClick={()=>setSection('agents')}>Edit team</button><button onClick={()=>setSection('guides')}>Edit guides</button><button onClick={()=>setSection('homepage')}>Edit homepage</button><button onClick={()=>setSection('media')}>Manage photos</button><button onClick={()=>setSection('testimonials')}>Manage testimonials</button><button onClick={()=>setSection('settings')}>Site settings</button></div></div></div>
 <div className="admin-panel admin-system"><p className="eyebrow">WEBSITE STATUS</p><div><span>MLS listings</span><strong>Managed by MLS Grid</strong></div><div><span>CRM leads</span><strong>Follow Up Boss when configured</strong></div><div><span>Storage</span><strong>Vercel Blob</strong></div><div><span>Last content save</span><strong>{data.updatedAt?new Date(data.updatedAt).toLocaleString():'—'}</strong></div></div>
 </div>
}
function Stat({n,label,onClick}:{n:number;label:string;onClick:()=>void}){return <button className="admin-stat" onClick={onClick}><strong>{n}</strong><span>{label}</span></button>}

function Leads({data,save,selectedLead,setSelectedLead}:{data:Data;save:(d:Data)=>Promise<void>;selectedLead:string|null;setSelectedLead:(v:string|null)=>void}){
 const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');
 const leads=data.leads.filter(l=>(filter==='all'||l.status===filter)&&(query===''||[l.name,l.email,l.phone,l.address,l.type,l.message].join(' ').toLowerCase().includes(query.toLowerCase())));
 const lead=selectedLead?data.leads.find(l=>l.id===selectedLead):null;
 async function updateLead(next:Lead){await save({...data,leads:data.leads.map(l=>l.id===next.id?next:l)});}
 return <div className="admin-list"><div className="admin-toolbar"><input placeholder="Search leads" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select></div>{leads.length?<table><thead><tr><th>Date</th><th>Lead</th><th>Type</th><th>Property</th><th>Status</th></tr></thead><tbody>{leads.map(l=><tr key={l.id} onClick={()=>setSelectedLead(l.id)} className="admin-click-row"><td>{new Date(l.createdAt).toLocaleDateString()}</td><td><strong>{l.name}</strong><br/><span>{l.email||l.phone}</span></td><td>{l.type}</td><td>{l.address||'—'}{l.listingId&&<small>MLS {l.listingId}</small>}</td><td><span className={'lead-status '+l.status}>{l.status}</span></td></tr>)}</tbody></table>:<p className="admin-muted">No leads match this filter.</p>}
 {lead&&<LeadDetail lead={lead} agents={data.agents} onClose={()=>setSelectedLead(null)} onSave={updateLead}/>}</div>
}
function LeadDetail({lead,agents,onClose,onSave}:{lead:Lead;agents:Agent[];onClose:()=>void;onSave:(l:Lead)=>Promise<void>}){
 const [draft,setDraft]=useState(lead);const [busy,setBusy]=useState(false);
 const save=async()=>{setBusy(true);await onSave(draft);setBusy(false);onClose()};
 return <div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="admin-modal"><button className="admin-modal-close" onClick={onClose}>×</button><p className="eyebrow">{draft.type}</p><h2>{draft.name}</h2><div className="admin-contact-actions">{draft.email&&<a href={'mailto:'+draft.email}>Email</a>}{draft.phone&&<a href={'tel:'+draft.phone.replace(/\D/g,'')}>Call</a>}{draft.address&&<a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(draft.address)} target="_blank" rel="noreferrer">Map</a>}</div><div className="admin-form-grid"><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Lead['status']})}><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select></label><label>Assigned agent<select value={draft.assignedAgent||''} onChange={e=>setDraft({...draft,assignedAgent:e.target.value||undefined})}><option value="">Unassigned</option>{agents.filter(a=>!a.hidden).map(a=><option key={a.slug} value={a.slug}>{a.name}</option>)}</select></label><label>Last contacted<input type="datetime-local" value={draft.lastContactedAt?draft.lastContactedAt.slice(0,16):''} onChange={e=>setDraft({...draft,lastContactedAt:e.target.value?new Date(e.target.value).toISOString():undefined})}/></label><label>Next follow-up<input type="datetime-local" value={draft.nextFollowUpAt?draft.nextFollowUpAt.slice(0,16):''} onChange={e=>setDraft({...draft,nextFollowUpAt:e.target.value?new Date(e.target.value).toISOString():undefined})}/></label></div><div className="admin-lead-facts"><div><span>Email</span><strong>{draft.email||'—'}</strong></div><div><span>Phone</span><strong>{draft.phone||'—'}</strong></div><div><span>Property</span><strong>{draft.address||'—'}</strong></div><div><span>Submitted</span><strong>{new Date(draft.createdAt).toLocaleString()}</strong></div></div><label>Message<textarea rows={5} value={draft.message||''} onChange={e=>setDraft({...draft,message:e.target.value})}/></label><label>Internal notes<textarea rows={5} value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="admin-modal-actions"><button className="button button-light" onClick={onClose}>Cancel</button><button className="button button-dark" onClick={save} disabled={busy}>{busy?'Saving…':'Save lead'}</button></div></div></div>
}

function Agents({data,save}:{data:Data;save:(d:Data)=>Promise<void>}){
 const [draft,setDraft]=useState(data.agents);
 const [saved,setSaved]=useState(false);
 const update=(i:number,key:string,value:any)=>setDraft(draft.map((a,n)=>n===i?{...a,[key]:value}:a));
 const saveAll=async()=>{await save({...data,agents:draft});setSaved(true);setTimeout(()=>setSaved(false),1800)};
 return <div><div className="admin-editor-head"><p className="admin-muted">Edit the information shown on team and agent pages. Photos are managed in Media.</p><button className="button button-dark" onClick={saveAll}>Save team</button>{saved&&<span className="admin-success">Saved.</span>}</div><div className="admin-edit-grid">{draft.map((a,i)=><article key={a.slug}><div className="admin-agent-heading"><div className="admin-thumb"><img src={a.photo} alt="" /></div><div><p className="eyebrow">{a.role}</p><h2>{a.name}</h2></div></div><label>Name<input value={a.name} onChange={e=>update(i,'name',e.target.value)}/></label><label>Role<input value={a.role} onChange={e=>update(i,'role',e.target.value)}/></label><label>Phone<input value={a.phone} onChange={e=>update(i,'phone',e.target.value)}/></label><label>Email<input type="email" value={a.email||''} onChange={e=>update(i,'email',e.target.value)}/></label><label>Market<input value={a.market} onChange={e=>update(i,'market',e.target.value)}/></label><label>Specialties<input value={a.specialties.join(', ')} onChange={e=>update(i,'specialties',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label><label>Short description<textarea rows={3} value={a.snapshot} onChange={e=>update(i,'snapshot',e.target.value)}/></label><label>Bio<textarea rows={8} value={a.bio} onChange={e=>update(i,'bio',e.target.value)}/></label><label>Review / profile note<textarea rows={4} value={a.review} onChange={e=>update(i,'review',e.target.value)}/></label><label className="admin-check"><input type="checkbox" checked={Boolean(a.hidden)} onChange={e=>update(i,'hidden',e.target.checked)}/> Hide this agent from the public team page</label></article>)}</div></div>
}

function Guides({data,save}:{data:Data;save:(d:Data)=>Promise<void>}){
 const [index,setIndex]=useState(0);const [draft,setDraft]=useState(data.guides);const [saved,setSaved]=useState(false);const g=draft[index];
 const set=(next:Guide)=>setDraft(draft.map((x,i)=>i===index?next:x));
 const saveAll=async()=>{await save({...data,guides:draft});setSaved(true);setTimeout(()=>setSaved(false),1800)};
 const addSection=()=>set({...g,sections:[...g.sections,{heading:'New section',body:''}]});
 return <div className="admin-editor-split"><div className="admin-editor-sidebar">{draft.map((x,i)=><button className={i===index?'active':''} key={x.slug} onClick={()=>setIndex(i)}><strong>{x.title}</strong><small>{x.draft?'Draft':'Published'}</small></button>)}</div><div className="admin-editor-body"><div className="admin-editor-head"><p className="admin-muted">Edit guide content, sources and publishing status.</p><div><button className="button button-dark" onClick={saveAll}>Save guides</button>{saved&&<span className="admin-success"> Saved.</span>}</div></div><label>Title<input value={g.title} onChange={e=>set({...g,title:e.target.value})}/></label><div className="admin-form-grid"><label>Category<input value={g.category} onChange={e=>set({...g,category:e.target.value})}/></label><label>Slug<input value={g.slug} onChange={e=>set({...g,slug:e.target.value})}/></label></div><label>Card description<textarea rows={3} value={g.description} onChange={e=>set({...g,description:e.target.value})}/></label><label>Intro<textarea rows={5} value={g.intro} onChange={e=>set({...g,intro:e.target.value})}/></label><label>Updated label<input value={g.updated} onChange={e=>set({...g,updated:e.target.value})}/></label><label className="admin-check"><input type="checkbox" checked={Boolean(g.draft)} onChange={e=>set({...g,draft:e.target.checked})}/> Save as draft</label><div className="admin-section-editor"><div className="admin-editor-head"><h3>Sections</h3><button className="admin-link-button" onClick={addSection}>+ Add section</button></div>{g.sections.map((s,i)=><div className="admin-content-block" key={i}><div className="admin-block-head"><strong>Section {i+1}</strong><button onClick={()=>set({...g,sections:g.sections.filter((_,n)=>n!==i)})}>Remove</button></div><label>Heading<input value={s.heading} onChange={e=>set({...g,sections:g.sections.map((x,n)=>n===i?{...x,heading:e.target.value}:x)})}/></label><label>Body<textarea rows={8} value={s.body} onChange={e=>set({...g,sections:g.sections.map((x,n)=>n===i?{...x,body:e.target.value}:x)})}/></label></div>)}</div><div className="admin-section-editor"><div className="admin-editor-head"><h3>Sources</h3><button className="admin-link-button" onClick={()=>set({...g,sources:[...(g.sources||[]),{label:'New source',url:'https://'}]})}>+ Add source</button></div>{(g.sources||[]).map((s,i)=><div className="admin-source-row" key={i}><input value={s.label} onChange={e=>set({...g,sources:g.sources?.map((x,n)=>n===i?{...x,label:e.target.value}:x)})}/><input value={s.url} onChange={e=>set({...g,sources:g.sources?.map((x,n)=>n===i?{...x,url:e.target.value}:x)})}/><button onClick={()=>set({...g,sources:g.sources?.filter((_,n)=>n!==i)})}>Remove</button></div>)}</div></div></div>
}

function Testimonials({data,save}:{data:Data;save:(d:Data)=>Promise<void>}){
 const [draft,setDraft]=useState(data.testimonials);const [saved,setSaved]=useState(false);
 const update=(i:number,key:string,value:any)=>setDraft(draft.map((x,n)=>n===i?{...x,[key]:value}:x));
 const saveAll=async()=>{await save({...data,testimonials:draft});setSaved(true);setTimeout(()=>setSaved(false),1800)};
 return <div><div className="admin-editor-head"><p className="admin-muted">Manage manually selected testimonials. Google reviews remain connected to Google separately.</p><button className="button button-dark" onClick={saveAll}>Save testimonials</button>{saved&&<span className="admin-success">Saved.</span>}</div><div className="admin-testimonials">{draft.sort((a,b)=>a.sort-b.sort).map((t,i)=><article key={t.id}><div className="admin-block-head"><strong>{t.name||'New testimonial'}</strong><button onClick={()=>setDraft(draft.filter((_,n)=>n!==i))}>Remove</button></div><div className="admin-form-grid"><label>Name<input value={t.name} onChange={e=>update(i,'name',e.target.value)}/></label><label>Source<input value={t.source} onChange={e=>update(i,'source',e.target.value)}/></label><label>Rating<input type="number" min="1" max="5" value={t.rating} onChange={e=>update(i,'rating',Number(e.target.value))}/></label><label>Order<input type="number" value={t.sort} onChange={e=>update(i,'sort',Number(e.target.value))}/></label></div><label>Quote<textarea rows={5} value={t.quote} onChange={e=>update(i,'quote',e.target.value)}/></label><label className="admin-check"><input type="checkbox" checked={t.featured} onChange={e=>update(i,'featured',e.target.checked)}/> Feature on the website</label></article>)}<button className="admin-add-button" onClick={()=>setDraft([...draft,{id:crypto.randomUUID(),name:'',quote:'',rating:5,source:'Client review',featured:false,sort:draft.length+1}])}>+ Add testimonial</button></div></div>
}

function Homepage({data,save}:{data:Data;save:(d:Data)=>Promise<void>}){
 const [s,setS]=useState(data.settings);const [saved,setSaved]=useState(false);const saveAll=async()=>{await save({...data,settings:s});setSaved(true);setTimeout(()=>setSaved(false),1800)};
 return <div className="admin-settings"><div className="admin-editor-head"><p className="admin-muted">Control the major editable content on the homepage.</p><button className="button button-dark" onClick={saveAll}>Save homepage</button>{saved&&<span className="admin-success">Saved.</span>}</div><label>Hero eyebrow<input value={s.heroEyebrow} onChange={e=>setS({...s,heroEyebrow:e.target.value})}/></label><label>Hero headline<input value={s.homepageHeadline} onChange={e=>setS({...s,homepageHeadline:e.target.value})}/></label><label>Hero description<textarea rows={4} value={s.heroDescription} onChange={e=>setS({...s,heroDescription:e.target.value})}/></label><label>Featured listings count<input type="number" min="1" max="12" value={s.featuredCount} onChange={e=>setS({...s,featuredCount:Math.max(1,Math.min(12,Number(e.target.value)||1))})}/></label><label>Local section heading<input value={s.localHeading} onChange={e=>setS({...s,localHeading:e.target.value})}/></label><label>Local section description<textarea rows={4} value={s.localDescription} onChange={e=>setS({...s,localDescription:e.target.value})}/></label><label>Local section image URL<input value={s.localImage} onChange={e=>setS({...s,localImage:e.target.value})}/></label></div>
}

function Media(){
 const [items,setItems]=useState<Media[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const load=()=>fetch('/api/admin/media',{cache:'no-store'}).then(r=>r.json()).then(d=>setItems(d.blobs||[])).catch(()=>setMessage('Unable to load media.'));
 useEffect(()=>{load()},[]);
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setMessage('Uploading…');const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/media',{method:'POST',body:fd});const d=await r.json();setBusy(false);setMessage(r.ok?'Uploaded.':d.error||'Upload failed.');if(r.ok)load();e.target.value='';}
 async function remove(pathname:string){if(!confirm('Delete this media file?'))return;const r=await fetch('/api/admin/media?pathname='+encodeURIComponent(pathname),{method:'DELETE'});setMessage(r.ok?'Deleted.':'Delete failed.');if(r.ok)load();}
 return <div><div className="admin-editor-head"><p className="admin-muted">Upload site images to private Vercel Blob storage. Use the resulting URL in content fields.</p><label className="button button-dark admin-upload-button">{busy?'Uploading…':'Upload image'}<input type="file" accept="image/*" onChange={upload} disabled={busy}/></label></div>{message&&<p className="admin-success">{message}</p>}<div className="admin-media-grid">{items.map(x=><article key={x.pathname}><img src={x.url} alt="" /><div><strong>{x.pathname.split('/').pop()}</strong><button onClick={()=>navigator.clipboard?.writeText(x.url)}>Copy URL</button><button onClick={()=>remove(x.pathname)}>Delete</button></div></article>)}</div>{!items.length&&<p className="admin-muted">No uploaded media yet.</p>}</div>
}

function Settings({data,save}:{data:Data;save:(d:Data)=>Promise<void>}){
 const [s,setS]=useState(data.settings);const [saved,setSaved]=useState(false);const saveAll=async()=>{await save({...data,settings:s});setSaved(true);setTimeout(()=>setSaved(false),1800)};
 return <div className="admin-settings"><div className="admin-editor-head"><p className="admin-muted">Business, contact, social and search settings.</p><button className="button button-dark" onClick={saveAll}>Save settings</button>{saved&&<span className="admin-success">Saved.</span>}</div><h3>Business</h3><label>Brokerage phone<input value={s.phone} onChange={e=>setS({...s,phone:e.target.value})}/></label><label>Office address<input value={s.address} onChange={e=>setS({...s,address:e.target.value})}/></label><label>Public email<input value={s.email} onChange={e=>setS({...s,email:e.target.value})}/></label><label>Office hours<input value={s.officeHours} onChange={e=>setS({...s,officeHours:e.target.value})}/></label><label>Lead notification email<input type="email" value={s.leadNotificationEmail} onChange={e=>setS({...s,leadNotificationEmail:e.target.value})}/></label><h3>Social & Google</h3><label>Facebook URL<input value={s.facebook} onChange={e=>setS({...s,facebook:e.target.value})}/></label><label>Instagram URL<input value={s.instagram} onChange={e=>setS({...s,instagram:e.target.value})}/></label><label>YouTube URL<input value={s.youtube} onChange={e=>setS({...s,youtube:e.target.value})}/></label><label>Google Business Profile URL<input value={s.googleBusiness} onChange={e=>setS({...s,googleBusiness:e.target.value})}/></label><h3>SEO</h3><label>Default title<input value={s.defaultTitle} onChange={e=>setS({...s,defaultTitle:e.target.value})}/></label><label>Default description<textarea rows={3} value={s.defaultDescription} onChange={e=>setS({...s,defaultDescription:e.target.value})}/></label><label>Social sharing image URL<input value={s.ogImage} onChange={e=>setS({...s,ogImage:e.target.value})}/></label></div>
}