'use client';
import Link from 'next/link';
import { useMemo, useRef, useState } from 'react';
import type { RESOProperty } from '../lib/mock-properties';
const TILE=256;
const DEFAULT_CENTER={lat:39.25,lon:-96.02};
function project(lat:number,lon:number,zoom:number){const scale=TILE*Math.pow(2,zoom);const x=((lon+180)/360)*scale;const sin=Math.sin(lat*Math.PI/180);const y=(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*scale;return{x,y}}
export function ListingMap({listings}:{listings:RESOProperty[]}){
 const [zoom,setZoom]=useState(9),[center,setCenter]=useState(DEFAULT_CENTER),[selected,setSelected]=useState<string|null>(null);
 const drag=useRef<{x:number;y:number;cx:number;cy:number}|null>(null);const centerPoint=useMemo(()=>project(center.lat,center.lon,zoom),[center,zoom]);
 const tileOrigin={x:Math.floor(centerPoint.x/TILE),y:Math.floor(centerPoint.y/TILE)},tileOffset={x:centerPoint.x-tileOrigin.x*TILE,y:centerPoint.y-tileOrigin.y*TILE};const tiles=[] as {tx:number;ty:number;wrappedX:number;x:number;y:number}[];
 for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++){const tx=tileOrigin.x+x,ty=tileOrigin.y+y,max=Math.pow(2,zoom),wrappedX=((tx%max)+max)%max;if(ty>=0&&ty<max)tiles.push({tx,ty,wrappedX,x:x*TILE-tileOffset.x+50,y:y*TILE-tileOffset.y+50})}
 function startDrag(e:React.PointerEvent<HTMLDivElement>){e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,cx:centerPoint.x,cy:centerPoint.y}}
 function moveDrag(e:React.PointerEvent<HTMLDivElement>){if(!drag.current)return;const scale=TILE*Math.pow(2,zoom),nextX=drag.current.cx-(e.clientX-drag.current.x),nextY=drag.current.cy-(e.clientY-drag.current.y),lon=nextX/scale*360-180,merc=.5-nextY/scale,lat=180/Math.PI*(2*Math.atan(Math.exp(merc*2*Math.PI))-Math.PI/2);setCenter({lat:Math.max(-85,Math.min(85,lat)),lon:((lon+540)%360)-180})}
 return <div className="listing-map-wrap"><div className="listing-map-toolbar"><div><p className="eyebrow">ACTIVE LISTINGS</p><h3>See where our listings are located.</h3></div><div className="listing-map-controls"><button type="button" onClick={()=>setZoom(z=>Math.min(13,z+1))} aria-label="Zoom in">+</button><button type="button" onClick={()=>setZoom(z=>Math.max(7,z-1))} aria-label="Zoom out">−</button></div></div><div className="listing-map" onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><div className="listing-map-tiles">{tiles.map(t=><img key={`${t.tx}-${t.ty}`} src={`https://tile.openstreetmap.org/${zoom}/${t.wrappedX}/${t.ty}.png`} alt="" draggable={false} style={{left:t.x,top:t.y}} />)}</div><div className="listing-map-markers">{listings.map(p=>{const point=project(p.Latitude,p.Longitude,zoom),left=point.x-centerPoint.x+50,top=point.y-centerPoint.y+50,active=selected===p.ListingId;return <button key={p.ListingId} type="button" className={`listing-marker${active?' is-selected':''}`} style={{left,top}} onPointerDown={e=>e.stopPropagation()} onClick={()=>setSelected(active?null:p.ListingId)} aria-label={`Show ${p.StreetNumber} ${p.StreetName}`}><span>$</span></button>})}</div>{selected&&(()=>{const p=listings.find(x=>x.ListingId===selected);if(!p)return null;return <div className="listing-map-card"><button type="button" onClick={()=>setSelected(null)} aria-label="Close">×</button><p className="eyebrow">FOR SALE</p><strong>${p.ListPrice.toLocaleString()}</strong><span>{p.StreetNumber} {p.StreetName}, {p.City}</span><span>{p.BedroomsTotal} beds · {p.BathroomsTotalInteger} baths · {p.LivingArea.toLocaleString()} sq ft</span><Link href={`/listings/${p.ListingId}`}>View listing →</Link></div>})()}<div className="listing-map-attribution">© OpenStreetMap contributors</div></div></div>
}
