export const metadata={title:'About SMRE'};
const areasOne=['St. Marys','Wamego','Manhattan','Topeka','Rossville'];
const areasTwo=['Silver Lake','St. George','Alma','Emmett','Maple Hill'];
export default function About(){return <>
<section className="section container narrow about-page"><div className="page-intro"><p className="eyebrow">ABOUT ST. MARY’S REAL ESTATE</p><h1>Real estate is personal. We think it should feel that way.</h1><p>Buying or selling a home can mean a lot of questions, a lot of money and a lot of decisions. SMRE is a local brokerage based in St. Marys, Kansas, serving communities throughout the Topeka–Manhattan area.</p></div>
<div className="about-copy"><p><strong>Maybe you are buying your first home.</strong> Maybe you are moving to the area, selling a place you have owned for years, looking for acreage, or trying to figure out what a property is actually worth. The situation is different for everyone.</p><p>That is why we do not think real estate should feel like a transaction where you get handed a set of keys and sent on your way. The useful part is having someone who knows the area, understands the property and will actually talk through the questions that come up along the way.</p><p>SMRE works with buyers and sellers on homes, land, acreage, investments, commercial property and new construction. The team works throughout St. Marys, Wamego, Topeka, Manhattan and the smaller communities in between, including with clients who are buying or selling from out of state.</p><p>Our approach is pretty simple: listen first, be straightforward, communicate clearly and stay involved from the first conversation through closing.</p></div>
<div className="about-areas"><div className="about-area-card"><h3>Areas we know</h3><p>{areasOne.join(' · ')}</p></div><div className="about-area-card"><h3>And the communities around them</h3><p>{areasTwo.join(' · ')}</p></div></div>
<div className="about-contact-card"><p className="eyebrow" style={{color:'#fff'}}>ST. MARYS OFFICE</p><h2>St. Mary’s Real Estate</h2><p>512 W Bertrand Ave<br />St Marys, KS 66536</p><p><a href="tel:7854652543">(785) 465-2543</a><br /><a href="mailto:admin@smre.info">admin@smre.info</a></p></div></section>
<section className="section container narrow"><div className="page-intro"><p className="eyebrow">CLIENT FEEDBACK</p><h2>What people say about working with SMRE.</h2><p>Published client reviews frequently talk about communication, patience, local guidance and hands-on help through the buying and selling process.</p></div><div className="about-review-grid"><blockquote>“Never missed a call from me throughout the entire two-month process.”<cite>— Patrick, published SMRE client review</cite></blockquote><blockquote>“They walked us through the process” and helped us with our first home purchase.<cite>— Jim, published SMRE client review</cite></blockquote><blockquote>“Michael Kirby made my purchase experience very easy” for an out-of-state buyer moving to St. Marys.<cite>— Anne, published SMRE client review</cite></blockquote></div><p className="google-rating"><strong>Google:</strong> 5.0 stars from 26 reviews at the time this site was researched.</p></section>
</>}
