export const metadata={title:'About SMRE'};
const areas=['St. Marys','Wamego','Manhattan','Topeka','Rossville','Silver Lake','St. George','Alma','Emmett','Maple Hill'];
export default function About(){return <>
<section className="section container narrow about-page"><div className="page-intro"><p className="eyebrow">ABOUT ST. MARY’S REAL ESTATE</p><h1>Local knowledge. Straightforward real estate.</h1><p>St. Mary’s Real Estate is a local brokerage based in St. Marys, Kansas, serving buyers and sellers throughout the Topeka–Manhattan area.</p></div>
<div className="about-copy"><p>Buying or selling property comes with a lot of questions. Our job is to make the process clear, keep communication straightforward, and help you make informed decisions about the property in front of you.</p><p>SMRE works with buyers and sellers on homes, land, acreage, investments, commercial property and new construction. Because we work across both small communities and larger markets, we understand the differences that matter from one property and one location to the next.</p><p>Our approach is simple: listen, communicate clearly, know the market, and stay involved from the first conversation through closing.</p></div>
<div className="about-areas"><div className="about-area-card"><h3>Areas we serve</h3><p>{areas.join(' · ')}</p></div></div>
<div className="about-contact-card"><p className="eyebrow" style={{color:'#fff'}}>ST. MARYS OFFICE</p><h2>St. Mary’s Real Estate</h2><p>512 W Bertrand Ave<br />St Marys, KS 66536</p><p><a href="tel:7854652543">(785) 465-2543</a><br /><a href="mailto:admin@smre.info">admin@smre.info</a></p></div></section>
<section className="section container narrow"><div className="page-intro"><p className="eyebrow">CLIENT FEEDBACK</p><h2>What people say about working with SMRE.</h2><p>Published client reviews frequently mention communication, patience, local guidance and hands-on help through the buying and selling process.</p></div><div className="about-review-grid"><blockquote>“Never missed a call from me throughout the entire two-month process.”<cite>— Patrick, published SMRE client review</cite></blockquote><blockquote>“They walked us through the process” and helped us with our first home purchase.<cite>— Jim, published SMRE client review</cite></blockquote><blockquote>“Michael Kirby made my purchase experience very easy” for an out-of-state buyer moving to St. Marys.<cite>— Anne, published SMRE client review</cite></blockquote></div><p className="google-rating"><strong>Google:</strong> 5.0 stars from 26 reviews at the time this site was researched.</p></section>
</>}
